// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// source: {{ .File.InputPath }}

package {{ pkg .File }}

import (
    pbfieldmask "github.com/yeqown/protoc-gen-fieldmask/proto/fieldmask"
    fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

{{ range $idx, $pair := .FieldMaskPairs }}
    {{ if or (eq $pair.FieldMaskOption.In.Gen true) (eq $pair.FieldMaskOption.Out.Gen true) }}
        {{ template "fm" . }}
    {{ end }}

    {{ if eq $pair.FieldMaskOption.In.Gen true }}
        {{ template "fm.in" . }}
    {{ end }}

    {{ if eq $pair.FieldMaskOption.Out.Gen true }}
        {{ template "fm.out" . }}
    {{ end }}
{{ end }}
