// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// source: {{ .File.InputPath }}

package {{ pkg .File }}

import (
    pbfieldmask "github.com/yeqown/protoc-gen-fieldmask/proto/fieldmask"
    "google.golang.org/protobuf/proto"
    "google.golang.org/protobuf/reflect/protoreflect"
    fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

{{ range .FieldMaskPairs }}{{ template "message.tpl" . }}
{{ end }}
