// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// versions:
//  protoc-gen-fieldmask v0.4.1
//  source: examples/proto/user.proto

package userv1

import (
	pgfmpb "github.com/yeqown/protoc-gen-fieldmask/protobuf"
	"google.golang.org/protobuf/reflect/protoreflect"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

// ============================================================================
// GetUser FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for GetUserRequest
func (x *GetUserRequest) FieldMask() *GetUser_FieldMask {
	return newGetUser_FieldMask(x, x.Fm)
}

// newGetUser_FieldMask creates a new FieldMask with the given fieldmask
func newGetUser_FieldMask(msg *GetUserRequest, fieldmask *fieldmaskpb.FieldMask) *GetUser_FieldMask {
	fm := &GetUser_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// GetUser_FieldMask provides helper functions to deal with FieldMask.
type GetUser_FieldMask struct {
	msg  *GetUserRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *GetUser_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *GetUser_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *GetUser_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *GetUser_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *GetUser_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *GetUser_FieldMask) Request() *GetUserRequest_Req {
	return &GetUserRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *GetUser_FieldMask) Response() *GetUserRequest_Res {
	return &GetUserRequest_Res{
		fm: fm,
	}
}

// GetUserRequest_Req handles request field masking
type GetUserRequest_Req struct {
	fm *GetUser_FieldMask
}

// MaskUserId marks the UserId field in the request
func (r *GetUserRequest_Req) MaskUserId() {
	r.fm.setReqFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the request
func (r *GetUserRequest_Req) MaskedUserId() bool {
	return r.fm.hasReqFieldPath("user_id")
}

// GetUserRequest_Res handles response field masking
type GetUserRequest_Res struct {
	fm *GetUser_FieldMask
}

// Apply applies the field mask to the response message
func (r *GetUserRequest_Res) Apply(resp *GetUserResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskUserId marks the UserId field in the response
func (r *GetUserRequest_Res) MaskUserId() {
	r.fm.setResFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the response
func (r *GetUserRequest_Res) MaskedUserId() bool {
	return r.fm.hasResFieldPath("user_id")
}

// MaskUsername marks the Username field in the response
func (r *GetUserRequest_Res) MaskUsername() {
	r.fm.setResFieldPath("username")
}

// MaskedUsername checks if Username is marked in the response
func (r *GetUserRequest_Res) MaskedUsername() bool {
	return r.fm.hasResFieldPath("username")
}

// MaskEmail marks the Email field in the response
func (r *GetUserRequest_Res) MaskEmail() {
	r.fm.setResFieldPath("email")
}

// MaskedEmail checks if Email is marked in the response
func (r *GetUserRequest_Res) MaskedEmail() bool {
	return r.fm.hasResFieldPath("email")
}

// MaskPhone marks the Phone field in the response
func (r *GetUserRequest_Res) MaskPhone() {
	r.fm.setResFieldPath("phone")
}

// MaskedPhone checks if Phone is marked in the response
func (r *GetUserRequest_Res) MaskedPhone() bool {
	return r.fm.hasResFieldPath("phone")
}

// MaskAvatarUrl marks the AvatarUrl field in the response
func (r *GetUserRequest_Res) MaskAvatarUrl() {
	r.fm.setResFieldPath("avatar_url")
}

// MaskedAvatarUrl checks if AvatarUrl is marked in the response
func (r *GetUserRequest_Res) MaskedAvatarUrl() bool {
	return r.fm.hasResFieldPath("avatar_url")
}

// MaskBio marks the Bio field in the response
func (r *GetUserRequest_Res) MaskBio() {
	r.fm.setResFieldPath("bio")
}

// MaskedBio checks if Bio is marked in the response
func (r *GetUserRequest_Res) MaskedBio() bool {
	return r.fm.hasResFieldPath("bio")
}

// MaskCreatedAt marks the CreatedAt field in the response
func (r *GetUserRequest_Res) MaskCreatedAt() {
	r.fm.setResFieldPath("created_at")
}

// MaskedCreatedAt checks if CreatedAt is marked in the response
func (r *GetUserRequest_Res) MaskedCreatedAt() bool {
	return r.fm.hasResFieldPath("created_at")
}

// MaskUpdatedAt marks the UpdatedAt field in the response
func (r *GetUserRequest_Res) MaskUpdatedAt() {
	r.fm.setResFieldPath("updated_at")
}

// MaskedUpdatedAt checks if UpdatedAt is marked in the response
func (r *GetUserRequest_Res) MaskedUpdatedAt() bool {
	return r.fm.hasResFieldPath("updated_at")
}

// ============================================================================
// UpdateUser FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for UpdateUserRequest
func (x *UpdateUserRequest) FieldMask() *UpdateUser_FieldMask {
	return newUpdateUser_FieldMask(x, x.Fm)
}

// newUpdateUser_FieldMask creates a new FieldMask with the given fieldmask
func newUpdateUser_FieldMask(msg *UpdateUserRequest, fieldmask *fieldmaskpb.FieldMask) *UpdateUser_FieldMask {
	fm := &UpdateUser_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_PRUNE,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// UpdateUser_FieldMask provides helper functions to deal with FieldMask.
type UpdateUser_FieldMask struct {
	msg  *UpdateUserRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *UpdateUser_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *UpdateUser_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *UpdateUser_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *UpdateUser_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *UpdateUser_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *UpdateUser_FieldMask) Request() *UpdateUserRequest_Req {
	return &UpdateUserRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *UpdateUser_FieldMask) Response() *UpdateUserRequest_Res {
	return &UpdateUserRequest_Res{
		fm: fm,
	}
}

// UpdateUserRequest_Req handles request field masking
type UpdateUserRequest_Req struct {
	fm *UpdateUser_FieldMask
}

// MaskUsername marks the Username field in the request
func (r *UpdateUserRequest_Req) MaskUsername() {
	r.fm.setReqFieldPath("username")
}

// MaskedUsername checks if Username is marked in the request
func (r *UpdateUserRequest_Req) MaskedUsername() bool {
	return r.fm.hasReqFieldPath("username")
}

// MaskEmail marks the Email field in the request
func (r *UpdateUserRequest_Req) MaskEmail() {
	r.fm.setReqFieldPath("email")
}

// MaskedEmail checks if Email is marked in the request
func (r *UpdateUserRequest_Req) MaskedEmail() bool {
	return r.fm.hasReqFieldPath("email")
}

// MaskPhone marks the Phone field in the request
func (r *UpdateUserRequest_Req) MaskPhone() {
	r.fm.setReqFieldPath("phone")
}

// MaskedPhone checks if Phone is marked in the request
func (r *UpdateUserRequest_Req) MaskedPhone() bool {
	return r.fm.hasReqFieldPath("phone")
}

// MaskAvatarUrl marks the AvatarUrl field in the request
func (r *UpdateUserRequest_Req) MaskAvatarUrl() {
	r.fm.setReqFieldPath("avatar_url")
}

// MaskedAvatarUrl checks if AvatarUrl is marked in the request
func (r *UpdateUserRequest_Req) MaskedAvatarUrl() bool {
	return r.fm.hasReqFieldPath("avatar_url")
}

// MaskBio marks the Bio field in the request
func (r *UpdateUserRequest_Req) MaskBio() {
	r.fm.setReqFieldPath("bio")
}

// MaskedBio checks if Bio is marked in the request
func (r *UpdateUserRequest_Req) MaskedBio() bool {
	return r.fm.hasReqFieldPath("bio")
}

// UpdateUserRequest_Res handles response field masking
type UpdateUserRequest_Res struct {
	fm *UpdateUser_FieldMask
}

// Apply applies the field mask to the response message
func (r *UpdateUserRequest_Res) Apply(resp *UpdateUserResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskUserId marks the UserId field in the response
func (r *UpdateUserRequest_Res) MaskUserId() {
	r.fm.setResFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the response
func (r *UpdateUserRequest_Res) MaskedUserId() bool {
	return r.fm.hasResFieldPath("user_id")
}

// MaskUsername marks the Username field in the response
func (r *UpdateUserRequest_Res) MaskUsername() {
	r.fm.setResFieldPath("username")
}

// MaskedUsername checks if Username is marked in the response
func (r *UpdateUserRequest_Res) MaskedUsername() bool {
	return r.fm.hasResFieldPath("username")
}

// MaskEmail marks the Email field in the response
func (r *UpdateUserRequest_Res) MaskEmail() {
	r.fm.setResFieldPath("email")
}

// MaskedEmail checks if Email is marked in the response
func (r *UpdateUserRequest_Res) MaskedEmail() bool {
	return r.fm.hasResFieldPath("email")
}

// MaskPhone marks the Phone field in the response
func (r *UpdateUserRequest_Res) MaskPhone() {
	r.fm.setResFieldPath("phone")
}

// MaskedPhone checks if Phone is marked in the response
func (r *UpdateUserRequest_Res) MaskedPhone() bool {
	return r.fm.hasResFieldPath("phone")
}

// MaskAvatarUrl marks the AvatarUrl field in the response
func (r *UpdateUserRequest_Res) MaskAvatarUrl() {
	r.fm.setResFieldPath("avatar_url")
}

// MaskedAvatarUrl checks if AvatarUrl is marked in the response
func (r *UpdateUserRequest_Res) MaskedAvatarUrl() bool {
	return r.fm.hasResFieldPath("avatar_url")
}

// MaskBio marks the Bio field in the response
func (r *UpdateUserRequest_Res) MaskBio() {
	r.fm.setResFieldPath("bio")
}

// MaskedBio checks if Bio is marked in the response
func (r *UpdateUserRequest_Res) MaskedBio() bool {
	return r.fm.hasResFieldPath("bio")
}

// MaskUpdatedAt marks the UpdatedAt field in the response
func (r *UpdateUserRequest_Res) MaskUpdatedAt() {
	r.fm.setResFieldPath("updated_at")
}

// MaskedUpdatedAt checks if UpdatedAt is marked in the response
func (r *UpdateUserRequest_Res) MaskedUpdatedAt() bool {
	return r.fm.hasResFieldPath("updated_at")
}
