// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// versions:
//  protoc-gen-fieldmask v0.4.1
//  source: tests/example.proto

package example

import (
	pgfmpb "github.com/yeqown/protoc-gen-fieldmask/protobuf"
	"google.golang.org/protobuf/reflect/protoreflect"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

// ============================================================================
// GetUser FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for GetUserRequest
func (x *GetUserRequest) FieldMask() *GetUser_FieldMask {
	return newGetUser_FieldMask(x, x.Fm)
}

// newGetUser_FieldMask creates a new FieldMask with the given fieldmask
func newGetUser_FieldMask(msg *GetUserRequest, fieldmask *fieldmaskpb.FieldMask) *GetUser_FieldMask {
	fm := &GetUser_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// GetUser_FieldMask provides helper functions to deal with FieldMask.
type GetUser_FieldMask struct {
	msg  *GetUserRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *GetUser_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *GetUser_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *GetUser_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *GetUser_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *GetUser_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *GetUser_FieldMask) Request() *GetUserRequest_Req {
	return &GetUserRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *GetUser_FieldMask) Response() *GetUserRequest_Res {
	return &GetUserRequest_Res{
		fm: fm,
	}
}

// GetUserRequest_Req handles request field masking
type GetUserRequest_Req struct {
	fm *GetUser_FieldMask
}

// MaskUserId marks the UserId field in the request
func (r *GetUserRequest_Req) MaskUserId() {
	r.fm.setReqFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the request
func (r *GetUserRequest_Req) MaskedUserId() bool {
	return r.fm.hasReqFieldPath("user_id")
}

// GetUserRequest_Res handles response field masking
type GetUserRequest_Res struct {
	fm *GetUser_FieldMask
}

// Apply applies the field mask to the response message
func (r *GetUserRequest_Res) Apply(resp *GetUserResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskUserId marks the UserId field in the response
func (r *GetUserRequest_Res) MaskUserId() {
	r.fm.setResFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the response
func (r *GetUserRequest_Res) MaskedUserId() bool {
	return r.fm.hasResFieldPath("user_id")
}

// MaskUsername marks the Username field in the response
func (r *GetUserRequest_Res) MaskUsername() {
	r.fm.setResFieldPath("username")
}

// MaskedUsername checks if Username is marked in the response
func (r *GetUserRequest_Res) MaskedUsername() bool {
	return r.fm.hasResFieldPath("username")
}

// MaskEmail marks the Email field in the response
func (r *GetUserRequest_Res) MaskEmail() {
	r.fm.setResFieldPath("email")
}

// MaskedEmail checks if Email is marked in the response
func (r *GetUserRequest_Res) MaskedEmail() bool {
	return r.fm.hasResFieldPath("email")
}

// MaskAddress_UserId marks the UserId field in nested Address
func (r *GetUserRequest_Res) MaskAddress_UserId() {
	r.fm.setResFieldPath("address.user_id")
}

// MaskedAddress_UserId checks if UserId is marked in the response
func (r *GetUserRequest_Res) MaskedAddress_UserId() bool {
	return r.fm.hasResFieldPath("address.user_id")
}

// MaskAddress_Username marks the Username field in nested Address
func (r *GetUserRequest_Res) MaskAddress_Username() {
	r.fm.setResFieldPath("address.username")
}

// MaskedAddress_Username checks if Username is marked in the response
func (r *GetUserRequest_Res) MaskedAddress_Username() bool {
	return r.fm.hasResFieldPath("address.username")
}

// MaskAddress_Email marks the Email field in nested Address
func (r *GetUserRequest_Res) MaskAddress_Email() {
	r.fm.setResFieldPath("address.email")
}

// MaskedAddress_Email checks if Email is marked in the response
func (r *GetUserRequest_Res) MaskedAddress_Email() bool {
	return r.fm.hasResFieldPath("address.email")
}

// MaskAddress_Address marks the Address field in nested Address
func (r *GetUserRequest_Res) MaskAddress_Address() {
	r.fm.setResFieldPath("address.address")
}

// MaskedAddress_Address checks if Address is marked in the response
func (r *GetUserRequest_Res) MaskedAddress_Address() bool {
	return r.fm.hasResFieldPath("address.address")
}

// MaskAddress_Contact marks the Contact field in nested Address
func (r *GetUserRequest_Res) MaskAddress_Contact() {
	r.fm.setResFieldPath("address.contact")
}

// MaskedAddress_Contact checks if Contact is marked in the response
func (r *GetUserRequest_Res) MaskedAddress_Contact() bool {
	return r.fm.hasResFieldPath("address.contact")
}

// MaskContact marks the Contact field in the response
func (r *GetUserRequest_Res) MaskContact() {
	r.fm.setResFieldPath("contact")
}

// MaskedContact checks if Contact is marked in the response
func (r *GetUserRequest_Res) MaskedContact() bool {
	return r.fm.hasResFieldPath("contact")
}

// ============================================================================
// UpdateUser FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for UpdateUserRequest
func (x *UpdateUserRequest) FieldMask() *UpdateUser_FieldMask {
	return newUpdateUser_FieldMask(x, x.Fm)
}

// newUpdateUser_FieldMask creates a new FieldMask with the given fieldmask
func newUpdateUser_FieldMask(msg *UpdateUserRequest, fieldmask *fieldmaskpb.FieldMask) *UpdateUser_FieldMask {
	fm := &UpdateUser_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_PRUNE,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// UpdateUser_FieldMask provides helper functions to deal with FieldMask.
type UpdateUser_FieldMask struct {
	msg  *UpdateUserRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *UpdateUser_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *UpdateUser_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *UpdateUser_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *UpdateUser_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *UpdateUser_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *UpdateUser_FieldMask) Request() *UpdateUserRequest_Req {
	return &UpdateUserRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *UpdateUser_FieldMask) Response() *UpdateUserRequest_Res {
	return &UpdateUserRequest_Res{
		fm: fm,
	}
}

// UpdateUserRequest_Req handles request field masking
type UpdateUserRequest_Req struct {
	fm *UpdateUser_FieldMask
}

// MaskUserId marks the UserId field in the request
func (r *UpdateUserRequest_Req) MaskUserId() {
	r.fm.setReqFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the request
func (r *UpdateUserRequest_Req) MaskedUserId() bool {
	return r.fm.hasReqFieldPath("user_id")
}

// MaskUsername marks the Username field in the request
func (r *UpdateUserRequest_Req) MaskUsername() {
	r.fm.setReqFieldPath("username")
}

// MaskedUsername checks if Username is marked in the request
func (r *UpdateUserRequest_Req) MaskedUsername() bool {
	return r.fm.hasReqFieldPath("username")
}

// MaskEmail marks the Email field in the request
func (r *UpdateUserRequest_Req) MaskEmail() {
	r.fm.setReqFieldPath("email")
}

// MaskedEmail checks if Email is marked in the request
func (r *UpdateUserRequest_Req) MaskedEmail() bool {
	return r.fm.hasReqFieldPath("email")
}

// MaskAddress_UserId marks the UserId field in nested Address
func (r *UpdateUserRequest_Req) MaskAddress_UserId() {
	r.fm.setReqFieldPath("address.user_id")
}

// MaskedAddress_UserId checks if UserId is marked in the request
func (r *UpdateUserRequest_Req) MaskedAddress_UserId() bool {
	return r.fm.hasReqFieldPath("address.user_id")
}

// MaskAddress_Username marks the Username field in nested Address
func (r *UpdateUserRequest_Req) MaskAddress_Username() {
	r.fm.setReqFieldPath("address.username")
}

// MaskedAddress_Username checks if Username is marked in the request
func (r *UpdateUserRequest_Req) MaskedAddress_Username() bool {
	return r.fm.hasReqFieldPath("address.username")
}

// MaskAddress_Email marks the Email field in nested Address
func (r *UpdateUserRequest_Req) MaskAddress_Email() {
	r.fm.setReqFieldPath("address.email")
}

// MaskedAddress_Email checks if Email is marked in the request
func (r *UpdateUserRequest_Req) MaskedAddress_Email() bool {
	return r.fm.hasReqFieldPath("address.email")
}

// MaskAddress_Address marks the Address field in nested Address
func (r *UpdateUserRequest_Req) MaskAddress_Address() {
	r.fm.setReqFieldPath("address.address")
}

// MaskedAddress_Address checks if Address is marked in the request
func (r *UpdateUserRequest_Req) MaskedAddress_Address() bool {
	return r.fm.hasReqFieldPath("address.address")
}

// UpdateUserRequest_Res handles response field masking
type UpdateUserRequest_Res struct {
	fm *UpdateUser_FieldMask
}

// Apply applies the field mask to the response message
func (r *UpdateUserRequest_Res) Apply(resp *UpdateUserResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskUserId marks the UserId field in the response
func (r *UpdateUserRequest_Res) MaskUserId() {
	r.fm.setResFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the response
func (r *UpdateUserRequest_Res) MaskedUserId() bool {
	return r.fm.hasResFieldPath("user_id")
}

// MaskVersion marks the Version field in the response
func (r *UpdateUserRequest_Res) MaskVersion() {
	r.fm.setResFieldPath("version")
}

// MaskedVersion checks if Version is marked in the response
func (r *UpdateUserRequest_Res) MaskedVersion() bool {
	return r.fm.hasResFieldPath("version")
}

// MaskUpdatedAt marks the UpdatedAt field in the response
func (r *UpdateUserRequest_Res) MaskUpdatedAt() {
	r.fm.setResFieldPath("updated_at")
}

// MaskedUpdatedAt checks if UpdatedAt is marked in the response
func (r *UpdateUserRequest_Res) MaskedUpdatedAt() bool {
	return r.fm.hasResFieldPath("updated_at")
}

// ============================================================================
// CreateUser FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for CreateUserRequest
func (x *CreateUserRequest) FieldMask() *CreateUser_FieldMask {
	return newCreateUser_FieldMask(x, x.Mask)
}

// newCreateUser_FieldMask creates a new FieldMask with the given fieldmask
func newCreateUser_FieldMask(msg *CreateUserRequest, fieldmask *fieldmaskpb.FieldMask) *CreateUser_FieldMask {
	fm := &CreateUser_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// CreateUser_FieldMask provides helper functions to deal with FieldMask.
type CreateUser_FieldMask struct {
	msg  *CreateUserRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *CreateUser_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *CreateUser_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *CreateUser_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *CreateUser_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *CreateUser_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *CreateUser_FieldMask) Request() *CreateUserRequest_Req {
	return &CreateUserRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *CreateUser_FieldMask) Response() *CreateUserRequest_Res {
	return &CreateUserRequest_Res{
		fm: fm,
	}
}

// CreateUserRequest_Req handles request field masking
type CreateUserRequest_Req struct {
	fm *CreateUser_FieldMask
}

// MaskUsername marks the Username field in the request
func (r *CreateUserRequest_Req) MaskUsername() {
	r.fm.setReqFieldPath("username")
}

// MaskedUsername checks if Username is marked in the request
func (r *CreateUserRequest_Req) MaskedUsername() bool {
	return r.fm.hasReqFieldPath("username")
}

// MaskEmail marks the Email field in the request
func (r *CreateUserRequest_Req) MaskEmail() {
	r.fm.setReqFieldPath("email")
}

// MaskedEmail checks if Email is marked in the request
func (r *CreateUserRequest_Req) MaskedEmail() bool {
	return r.fm.hasReqFieldPath("email")
}

// MaskAddress_Username marks the Username field in nested Address
func (r *CreateUserRequest_Req) MaskAddress_Username() {
	r.fm.setReqFieldPath("address.username")
}

// MaskedAddress_Username checks if Username is marked in the request
func (r *CreateUserRequest_Req) MaskedAddress_Username() bool {
	return r.fm.hasReqFieldPath("address.username")
}

// MaskAddress_Email marks the Email field in nested Address
func (r *CreateUserRequest_Req) MaskAddress_Email() {
	r.fm.setReqFieldPath("address.email")
}

// MaskedAddress_Email checks if Email is marked in the request
func (r *CreateUserRequest_Req) MaskedAddress_Email() bool {
	return r.fm.hasReqFieldPath("address.email")
}

// MaskAddress_Address marks the Address field in nested Address
func (r *CreateUserRequest_Req) MaskAddress_Address() {
	r.fm.setReqFieldPath("address.address")
}

// MaskedAddress_Address checks if Address is marked in the request
func (r *CreateUserRequest_Req) MaskedAddress_Address() bool {
	return r.fm.hasReqFieldPath("address.address")
}

// CreateUserRequest_Res handles response field masking
type CreateUserRequest_Res struct {
	fm *CreateUser_FieldMask
}

// Apply applies the field mask to the response message
func (r *CreateUserRequest_Res) Apply(resp *CreateUserResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskUserId marks the UserId field in the response
func (r *CreateUserRequest_Res) MaskUserId() {
	r.fm.setResFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the response
func (r *CreateUserRequest_Res) MaskedUserId() bool {
	return r.fm.hasResFieldPath("user_id")
}

// MaskUsername marks the Username field in the response
func (r *CreateUserRequest_Res) MaskUsername() {
	r.fm.setResFieldPath("username")
}

// MaskedUsername checks if Username is marked in the response
func (r *CreateUserRequest_Res) MaskedUsername() bool {
	return r.fm.hasResFieldPath("username")
}

// MaskEmail marks the Email field in the response
func (r *CreateUserRequest_Res) MaskEmail() {
	r.fm.setResFieldPath("email")
}

// MaskedEmail checks if Email is marked in the response
func (r *CreateUserRequest_Res) MaskedEmail() bool {
	return r.fm.hasResFieldPath("email")
}

// MaskAddress_UserId marks the UserId field in nested Address
func (r *CreateUserRequest_Res) MaskAddress_UserId() {
	r.fm.setResFieldPath("address.user_id")
}

// MaskedAddress_UserId checks if UserId is marked in the response
func (r *CreateUserRequest_Res) MaskedAddress_UserId() bool {
	return r.fm.hasResFieldPath("address.user_id")
}

// MaskAddress_Username marks the Username field in nested Address
func (r *CreateUserRequest_Res) MaskAddress_Username() {
	r.fm.setResFieldPath("address.username")
}

// MaskedAddress_Username checks if Username is marked in the response
func (r *CreateUserRequest_Res) MaskedAddress_Username() bool {
	return r.fm.hasResFieldPath("address.username")
}

// MaskAddress_Email marks the Email field in nested Address
func (r *CreateUserRequest_Res) MaskAddress_Email() {
	r.fm.setResFieldPath("address.email")
}

// MaskedAddress_Email checks if Email is marked in the response
func (r *CreateUserRequest_Res) MaskedAddress_Email() bool {
	return r.fm.hasResFieldPath("address.email")
}

// MaskAddress_Address marks the Address field in nested Address
func (r *CreateUserRequest_Res) MaskAddress_Address() {
	r.fm.setResFieldPath("address.address")
}

// MaskedAddress_Address checks if Address is marked in the response
func (r *CreateUserRequest_Res) MaskedAddress_Address() bool {
	return r.fm.hasResFieldPath("address.address")
}

// MaskAddress_CreatedAt marks the CreatedAt field in nested Address
func (r *CreateUserRequest_Res) MaskAddress_CreatedAt() {
	r.fm.setResFieldPath("address.created_at")
}

// MaskedAddress_CreatedAt checks if CreatedAt is marked in the response
func (r *CreateUserRequest_Res) MaskedAddress_CreatedAt() bool {
	return r.fm.hasResFieldPath("address.created_at")
}

// MaskCreatedAt marks the CreatedAt field in the response
func (r *CreateUserRequest_Res) MaskCreatedAt() {
	r.fm.setResFieldPath("created_at")
}

// MaskedCreatedAt checks if CreatedAt is marked in the response
func (r *CreateUserRequest_Res) MaskedCreatedAt() bool {
	return r.fm.hasResFieldPath("created_at")
}

// ============================================================================
// GetUserByStatus FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for GetUserByStatusRequest
func (x *GetUserByStatusRequest) FieldMask() *GetUserByStatus_FieldMask {
	return newGetUserByStatus_FieldMask(x, x.Fm)
}

// newGetUserByStatus_FieldMask creates a new FieldMask with the given fieldmask
func newGetUserByStatus_FieldMask(msg *GetUserByStatusRequest, fieldmask *fieldmaskpb.FieldMask) *GetUserByStatus_FieldMask {
	fm := &GetUserByStatus_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// GetUserByStatus_FieldMask provides helper functions to deal with FieldMask.
type GetUserByStatus_FieldMask struct {
	msg  *GetUserByStatusRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *GetUserByStatus_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *GetUserByStatus_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *GetUserByStatus_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *GetUserByStatus_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *GetUserByStatus_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *GetUserByStatus_FieldMask) Request() *GetUserByStatusRequest_Req {
	return &GetUserByStatusRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *GetUserByStatus_FieldMask) Response() *GetUserByStatusRequest_Res {
	return &GetUserByStatusRequest_Res{
		fm: fm,
	}
}

// GetUserByStatusRequest_Req handles request field masking
type GetUserByStatusRequest_Req struct {
	fm *GetUserByStatus_FieldMask
}

// MaskStatus marks the Status field in the request
func (r *GetUserByStatusRequest_Req) MaskStatus() {
	r.fm.setReqFieldPath("status")
}

// MaskedStatus checks if Status is marked in the request
func (r *GetUserByStatusRequest_Req) MaskedStatus() bool {
	return r.fm.hasReqFieldPath("status")
}

// GetUserByStatusRequest_Res handles response field masking
type GetUserByStatusRequest_Res struct {
	fm *GetUserByStatus_FieldMask
}

// Apply applies the field mask to the response message
func (r *GetUserByStatusRequest_Res) Apply(resp *GetUserByStatusResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskUsers marks the Users field in the response
func (r *GetUserByStatusRequest_Res) MaskUsers() {
	r.fm.setResFieldPath("users")
}

// MaskedUsers checks if Users is marked in the response
func (r *GetUserByStatusRequest_Res) MaskedUsers() bool {
	return r.fm.hasResFieldPath("users")
}

// ============================================================================
// GetUserMetadata FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for GetUserMetadataRequest
func (x *GetUserMetadataRequest) FieldMask() *GetUserMetadata_FieldMask {
	return newGetUserMetadata_FieldMask(x, x.Fm)
}

// newGetUserMetadata_FieldMask creates a new FieldMask with the given fieldmask
func newGetUserMetadata_FieldMask(msg *GetUserMetadataRequest, fieldmask *fieldmaskpb.FieldMask) *GetUserMetadata_FieldMask {
	fm := &GetUserMetadata_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// GetUserMetadata_FieldMask provides helper functions to deal with FieldMask.
type GetUserMetadata_FieldMask struct {
	msg  *GetUserMetadataRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *GetUserMetadata_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *GetUserMetadata_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *GetUserMetadata_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *GetUserMetadata_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *GetUserMetadata_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *GetUserMetadata_FieldMask) Request() *GetUserMetadataRequest_Req {
	return &GetUserMetadataRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *GetUserMetadata_FieldMask) Response() *GetUserMetadataRequest_Res {
	return &GetUserMetadataRequest_Res{
		fm: fm,
	}
}

// GetUserMetadataRequest_Req handles request field masking
type GetUserMetadataRequest_Req struct {
	fm *GetUserMetadata_FieldMask
}

// MaskUserId marks the UserId field in the request
func (r *GetUserMetadataRequest_Req) MaskUserId() {
	r.fm.setReqFieldPath("user_id")
}

// MaskedUserId checks if UserId is marked in the request
func (r *GetUserMetadataRequest_Req) MaskedUserId() bool {
	return r.fm.hasReqFieldPath("user_id")
}

// GetUserMetadataRequest_Res handles response field masking
type GetUserMetadataRequest_Res struct {
	fm *GetUserMetadata_FieldMask
}

// Apply applies the field mask to the response message
func (r *GetUserMetadataRequest_Res) Apply(resp *GetUserMetadataResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskMetadata marks the Metadata field in the response
func (r *GetUserMetadataRequest_Res) MaskMetadata() {
	r.fm.setResFieldPath("metadata")
}

// MaskedMetadata checks if Metadata is marked in the response
func (r *GetUserMetadataRequest_Res) MaskedMetadata() bool {
	return r.fm.hasResFieldPath("metadata")
}

// MaskCounters marks the Counters field in the response
func (r *GetUserMetadataRequest_Res) MaskCounters() {
	r.fm.setResFieldPath("counters")
}

// MaskedCounters checks if Counters is marked in the response
func (r *GetUserMetadataRequest_Res) MaskedCounters() bool {
	return r.fm.hasResFieldPath("counters")
}

// ============================================================================
// GetUserOrOrganization FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for GetUserOrOrganizationRequest
func (x *GetUserOrOrganizationRequest) FieldMask() *GetUserOrOrganization_FieldMask {
	return newGetUserOrOrganization_FieldMask(x, x.Fm)
}

// newGetUserOrOrganization_FieldMask creates a new FieldMask with the given fieldmask
func newGetUserOrOrganization_FieldMask(msg *GetUserOrOrganizationRequest, fieldmask *fieldmaskpb.FieldMask) *GetUserOrOrganization_FieldMask {
	fm := &GetUserOrOrganization_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// GetUserOrOrganization_FieldMask provides helper functions to deal with FieldMask.
type GetUserOrOrganization_FieldMask struct {
	msg  *GetUserOrOrganizationRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *GetUserOrOrganization_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *GetUserOrOrganization_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *GetUserOrOrganization_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *GetUserOrOrganization_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *GetUserOrOrganization_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *GetUserOrOrganization_FieldMask) Request() *GetUserOrOrganizationRequest_Req {
	return &GetUserOrOrganizationRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *GetUserOrOrganization_FieldMask) Response() *GetUserOrOrganizationRequest_Res {
	return &GetUserOrOrganizationRequest_Res{
		fm: fm,
	}
}

// GetUserOrOrganizationRequest_Req handles request field masking
type GetUserOrOrganizationRequest_Req struct {
	fm *GetUserOrOrganization_FieldMask
}

// MaskRequestId marks the RequestId field in the request
func (r *GetUserOrOrganizationRequest_Req) MaskRequestId() {
	r.fm.setReqFieldPath("request_id")
}

// MaskedRequestId checks if RequestId is marked in the request
func (r *GetUserOrOrganizationRequest_Req) MaskedRequestId() bool {
	return r.fm.hasReqFieldPath("request_id")
}

// GetUserOrOrganizationRequest_Res handles response field masking
type GetUserOrOrganizationRequest_Res struct {
	fm *GetUserOrOrganization_FieldMask
}

// Apply applies the field mask to the response message
func (r *GetUserOrOrganizationRequest_Res) Apply(resp *GetUserOrOrganizationResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskId marks the Id field in the response
func (r *GetUserOrOrganizationRequest_Res) MaskId() {
	r.fm.setResFieldPath("id")
}

// MaskedId checks if Id is marked in the response
func (r *GetUserOrOrganizationRequest_Res) MaskedId() bool {
	return r.fm.hasResFieldPath("id")
}

// MaskName marks the Name field in the response
func (r *GetUserOrOrganizationRequest_Res) MaskName() {
	r.fm.setResFieldPath("name")
}

// MaskedName checks if Name is marked in the response
func (r *GetUserOrOrganizationRequest_Res) MaskedName() bool {
	return r.fm.hasResFieldPath("name")
}

// MaskType marks the Type field in the response
func (r *GetUserOrOrganizationRequest_Res) MaskType() {
	r.fm.setResFieldPath("type")
}

// MaskedType checks if Type is marked in the response
func (r *GetUserOrOrganizationRequest_Res) MaskedType() bool {
	return r.fm.hasResFieldPath("type")
}

// ============================================================================
// GetAddress FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for GetAddressRequest
func (x *GetAddressRequest) FieldMask() *GetAddress_FieldMask {
	return newGetAddress_FieldMask(x, x.Fm)
}

// newGetAddress_FieldMask creates a new FieldMask with the given fieldmask
func newGetAddress_FieldMask(msg *GetAddressRequest, fieldmask *fieldmaskpb.FieldMask) *GetAddress_FieldMask {
	fm := &GetAddress_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// GetAddress_FieldMask provides helper functions to deal with FieldMask.
type GetAddress_FieldMask struct {
	msg  *GetAddressRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *GetAddress_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *GetAddress_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *GetAddress_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *GetAddress_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *GetAddress_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *GetAddress_FieldMask) Request() *GetAddressRequest_Req {
	return &GetAddressRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *GetAddress_FieldMask) Response() *GetAddressRequest_Res {
	return &GetAddressRequest_Res{
		fm: fm,
	}
}

// GetAddressRequest_Req handles request field masking
type GetAddressRequest_Req struct {
	fm *GetAddress_FieldMask
}

// MaskAddressId marks the AddressId field in the request
func (r *GetAddressRequest_Req) MaskAddressId() {
	r.fm.setReqFieldPath("address_id")
}

// MaskedAddressId checks if AddressId is marked in the request
func (r *GetAddressRequest_Req) MaskedAddressId() bool {
	return r.fm.hasReqFieldPath("address_id")
}

// GetAddressRequest_Res handles response field masking
type GetAddressRequest_Res struct {
	fm *GetAddress_FieldMask
}

// Apply applies the field mask to the response message
func (r *GetAddressRequest_Res) Apply(resp *GetAddressResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskAddress_Address marks the Address field in nested Address
func (r *GetAddressRequest_Res) MaskAddress_Address() {
	r.fm.setResFieldPath("address.address")
}

// MaskedAddress_Address checks if Address is marked in the response
func (r *GetAddressRequest_Res) MaskedAddress_Address() bool {
	return r.fm.hasResFieldPath("address.address")
}

// ============================================================================
// ListUsers FieldMask API
// ============================================================================

// FieldMask creates a new FieldMask for ListUsersRequest
func (x *ListUsersRequest) FieldMask() *ListUsers_FieldMask {
	return newListUsers_FieldMask(x, x.Fm)
}

// newListUsers_FieldMask creates a new FieldMask with the given fieldmask
func newListUsers_FieldMask(msg *ListUsersRequest, fieldmask *fieldmaskpb.FieldMask) *ListUsers_FieldMask {
	fm := &ListUsers_FieldMask{
		msg:  msg,
		mode: pgfmpb.MaskMode_FILTER,
		mask: fieldmask,
		req:  make(map[string]struct{}),
		res:  make(map[string]struct{}),
	}

	// Parse existing paths to populate req and res maps
	if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
		paths := fieldmask.GetPaths()
		fm.req, fm.res = pgfmpb.SplitPaths(paths)
	}

	return fm
}

// ListUsers_FieldMask provides helper functions to deal with FieldMask.
type ListUsers_FieldMask struct {
	msg  *ListUsersRequest
	mode pgfmpb.MaskMode
	mask *fieldmaskpb.FieldMask
	req  map[string]struct{}
	res  map[string]struct{}
}

// ensureMaskInitialized initializes the mask field in the proto message if nil.
func (fm *ListUsers_FieldMask) ensureMaskInitialized() {
	if fm.mask != nil {
		return
	}
	// Use proto reflection to find and initialize the FieldMask field
	refl := fm.msg.ProtoReflect()
	descriptor := refl.Descriptor()
	fields := descriptor.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
			newMask := &fieldmaskpb.FieldMask{}
			refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
			fm.mask = newMask
			return
		}
	}
}

// setReqFieldPath adds a path to the request map
func (fm *ListUsers_FieldMask) setReqFieldPath(path string) {
	if fm.req == nil {
		fm.req = make(map[string]struct{})
	}
	fm.req[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddReqPathToFieldMask(fm.mask, path)
}

// setResFieldPath adds a path to the response map
func (fm *ListUsers_FieldMask) setResFieldPath(path string) {
	if fm.res == nil {
		fm.res = make(map[string]struct{})
	}
	fm.res[path] = struct{}{}
	fm.ensureMaskInitialized()
	pgfmpb.AddResPathToFieldMask(fm.mask, path)
}

// hasReqFieldPath checks if a path is in the request map
func (fm *ListUsers_FieldMask) hasReqFieldPath(path string) bool {
	if fm == nil || len(fm.req) == 0 {
		return false
	}
	_, exists := fm.req[path]
	return exists
}

// hasResFieldPath checks if a path is in the response map
func (fm *ListUsers_FieldMask) hasResFieldPath(path string) bool {
	if fm == nil || len(fm.res) == 0 {
		return false
	}
	_, exists := fm.res[path]
	return exists
}

// Request returns the Request mask operations
func (fm *ListUsers_FieldMask) Request() *ListUsersRequest_Req {
	return &ListUsersRequest_Req{
		fm: fm,
	}
}

// Response returns the Response mask operations
func (fm *ListUsers_FieldMask) Response() *ListUsersRequest_Res {
	return &ListUsersRequest_Res{
		fm: fm,
	}
}

// ListUsersRequest_Req handles request field masking
type ListUsersRequest_Req struct {
	fm *ListUsers_FieldMask
}

// MaskPageSize marks the PageSize field in the request
func (r *ListUsersRequest_Req) MaskPageSize() {
	r.fm.setReqFieldPath("page_size")
}

// MaskedPageSize checks if PageSize is marked in the request
func (r *ListUsersRequest_Req) MaskedPageSize() bool {
	return r.fm.hasReqFieldPath("page_size")
}

// MaskPageToken marks the PageToken field in the request
func (r *ListUsersRequest_Req) MaskPageToken() {
	r.fm.setReqFieldPath("page_token")
}

// MaskedPageToken checks if PageToken is marked in the request
func (r *ListUsersRequest_Req) MaskedPageToken() bool {
	return r.fm.hasReqFieldPath("page_token")
}

// ListUsersRequest_Res handles response field masking
type ListUsersRequest_Res struct {
	fm *ListUsers_FieldMask
}

// Apply applies the field mask to the response message
func (r *ListUsersRequest_Res) Apply(resp *ListUsersResponse) {
	if r.fm.mode == pgfmpb.MaskMode_PRUNE {
		pgfmpb.Prune(resp, r.fm.res)
		return
	}
	pgfmpb.Filter(resp, r.fm.res)
}

// MaskUsers marks the Users field in the response
func (r *ListUsersRequest_Res) MaskUsers() {
	r.fm.setResFieldPath("users")
}

// MaskedUsers checks if Users is marked in the response
func (r *ListUsersRequest_Res) MaskedUsers() bool {
	return r.fm.hasResFieldPath("users")
}

// MaskNextPageToken marks the NextPageToken field in the response
func (r *ListUsersRequest_Res) MaskNextPageToken() {
	r.fm.setResFieldPath("next_page_token")
}

// MaskedNextPageToken checks if NextPageToken is marked in the response
func (r *ListUsersRequest_Res) MaskedNextPageToken() bool {
	return r.fm.hasResFieldPath("next_page_token")
}

// MaskTotalCount marks the TotalCount field in the response
func (r *ListUsersRequest_Res) MaskTotalCount() {
	r.fm.setResFieldPath("total_count")
}

// MaskedTotalCount checks if TotalCount is marked in the response
func (r *ListUsersRequest_Res) MaskedTotalCount() bool {
	return r.fm.hasResFieldPath("total_count")
}
