// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.0
// source: protoc_gen_fieldmask/option.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaskMode int32

const (
	MaskMode_FILTER MaskMode = 0 // 被 mask 的字段才有效，其他字段会被忽略
	MaskMode_PRUNE  MaskMode = 1 // 被 mask 的字段会被忽略，其他字段会被返回
)

// Enum value maps for MaskMode.
var (
	MaskMode_name = map[int32]string{
		0: "FILTER",
		1: "PRUNE",
	}
	MaskMode_value = map[string]int32{
		"FILTER": 0,
		"PRUNE":  1,
	}
)

func (x MaskMode) Enum() *MaskMode {
	p := new(MaskMode)
	*p = x
	return p
}

func (x MaskMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaskMode) Descriptor() protoreflect.EnumDescriptor {
	return file_protoc_gen_fieldmask_option_proto_enumTypes[0].Descriptor()
}

func (MaskMode) Type() protoreflect.EnumType {
	return &file_protoc_gen_fieldmask_option_proto_enumTypes[0]
}

func (x MaskMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaskMode.Descriptor instead.
func (MaskMode) EnumDescriptor() ([]byte, []int) {
	return file_protoc_gen_fieldmask_option_proto_rawDescGZIP(), []int{0}
}

// MethodOptions 定义 RPC 方法级别的 field mask 配置
type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// request 中 field_mask 字段名称 (默认: "fm")
	FieldName string `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// mask 模式: FILTER 或 PRUNE (默认: FILTER)
	Mode MaskMode `protobuf:"varint,2,opt,name=mode,proto3,enum=protoc_gen_fieldmask.MaskMode" json:"mode,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_fieldmask_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_fieldmask_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_protoc_gen_fieldmask_option_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOptions) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *MethodOptions) GetMode() MaskMode {
	if x != nil {
		return x.Mode
	}
	return MaskMode_FILTER
}

// FieldOptions 定义单个字段的 mask 行为
type FieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否为该字段生成 mask 方法（默认: false）
	Mask bool `protobuf:"varint,1,opt,name=mask,proto3" json:"mask,omitempty"`
	// 是否为嵌套字段生成 mask 方法，仅当对应的字段类型为 Message 时有效（默认: false）
	Nested bool `protobuf:"varint,2,opt,name=nested,proto3" json:"nested,omitempty"`
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_fieldmask_option_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_fieldmask_option_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_protoc_gen_fieldmask_option_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOptions) GetMask() bool {
	if x != nil {
		return x.Mask
	}
	return false
}

func (x *FieldOptions) GetNested() bool {
	if x != nil {
		return x.Nested
	}
	return false
}

var file_protoc_gen_fieldmask_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         1142,
		Name:          "protoc_gen_fieldmask.rpc",
		Tag:           "bytes,1142,opt,name=rpc",
		Filename:      "protoc_gen_fieldmask/option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1142,
		Name:          "protoc_gen_fieldmask.field",
		Tag:           "bytes,1142,opt,name=field",
		Filename:      "protoc_gen_fieldmask/option.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional protoc_gen_fieldmask.MethodOptions rpc = 1142;
	E_Rpc = &file_protoc_gen_fieldmask_option_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional protoc_gen_fieldmask.FieldOptions field = 1142;
	E_Field = &file_protoc_gen_fieldmask_option_proto_extTypes[1]
)

var File_protoc_gen_fieldmask_option_proto protoreflect.FileDescriptor

var file_protoc_gen_fieldmask_option_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0d, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b,
	0x2e, 0x4d, 0x61, 0x73, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22,
	0x3a, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6d,
	0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2a, 0x21, 0x0a, 0x08, 0x4d,
	0x61, 0x73, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x49, 0x4c, 0x54, 0x45,
	0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x55, 0x4e, 0x45, 0x10, 0x01, 0x3a, 0x59,
	0x0a, 0x03, 0x72, 0x70, 0x63, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf6, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x6d,
	0x61, 0x73, 0x6b, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x03, 0x72, 0x70, 0x63, 0x88, 0x01, 0x01, 0x3a, 0x5b, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xf6, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x65, 0x71, 0x6f, 0x77, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x6d, 0x61, 0x73, 0x6b,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_gen_fieldmask_option_proto_rawDescOnce sync.Once
	file_protoc_gen_fieldmask_option_proto_rawDescData = file_protoc_gen_fieldmask_option_proto_rawDesc
)

func file_protoc_gen_fieldmask_option_proto_rawDescGZIP() []byte {
	file_protoc_gen_fieldmask_option_proto_rawDescOnce.Do(func() {
		file_protoc_gen_fieldmask_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_gen_fieldmask_option_proto_rawDescData)
	})
	return file_protoc_gen_fieldmask_option_proto_rawDescData
}

var file_protoc_gen_fieldmask_option_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protoc_gen_fieldmask_option_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoc_gen_fieldmask_option_proto_goTypes = []interface{}{
	(MaskMode)(0),                      // 0: protoc_gen_fieldmask.MaskMode
	(*MethodOptions)(nil),              // 1: protoc_gen_fieldmask.MethodOptions
	(*FieldOptions)(nil),               // 2: protoc_gen_fieldmask.FieldOptions
	(*descriptorpb.MethodOptions)(nil), // 3: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),  // 4: google.protobuf.FieldOptions
}
var file_protoc_gen_fieldmask_option_proto_depIdxs = []int32{
	0, // 0: protoc_gen_fieldmask.MethodOptions.mode:type_name -> protoc_gen_fieldmask.MaskMode
	3, // 1: protoc_gen_fieldmask.rpc:extendee -> google.protobuf.MethodOptions
	4, // 2: protoc_gen_fieldmask.field:extendee -> google.protobuf.FieldOptions
	1, // 3: protoc_gen_fieldmask.rpc:type_name -> protoc_gen_fieldmask.MethodOptions
	2, // 4: protoc_gen_fieldmask.field:type_name -> protoc_gen_fieldmask.FieldOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoc_gen_fieldmask_option_proto_init() }
func file_protoc_gen_fieldmask_option_proto_init() {
	if File_protoc_gen_fieldmask_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_gen_fieldmask_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_gen_fieldmask_option_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_gen_fieldmask_option_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_fieldmask_option_proto_goTypes,
		DependencyIndexes: file_protoc_gen_fieldmask_option_proto_depIdxs,
		EnumInfos:         file_protoc_gen_fieldmask_option_proto_enumTypes,
		MessageInfos:      file_protoc_gen_fieldmask_option_proto_msgTypes,
		ExtensionInfos:    file_protoc_gen_fieldmask_option_proto_extTypes,
	}.Build()
	File_protoc_gen_fieldmask_option_proto = out.File
	file_protoc_gen_fieldmask_option_proto_rawDesc = nil
	file_protoc_gen_fieldmask_option_proto_goTypes = nil
	file_protoc_gen_fieldmask_option_proto_depIdxs = nil
}
