// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// versions:
//  protoc-gen-fieldmask v0.4.1
//  source: {{ .File.InputPath }}

package {{ pkg .File }}

import (
	pgfmpb "github.com/yeqown/protoc-gen-fieldmask/protobuf"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	"google.golang.org/protobuf/reflect/protoreflect"

	{{ range $import := .ImportPaths }}
		{{ $import.PkgName}} "{{$import.ImportPath}}"
	{{ end }}
)

{{ range $idx, $pair := .FieldMaskPairs }}
	{{ $inMessageName := $pair.InMessage.Name }}
	{{ $outMessageName := $pair.OutMessage.Name }}
	{{ $fmField := $pair.FieldMaskField }}
	{{ $methodOpts := $pair.MethodOptions }}
	{{ $methodName := $pair.Method.Name }}

	// ============================================================================
	// {{ $methodName }} FieldMask API
	// ============================================================================

	// FieldMask creates a new FieldMask for {{ $inMessageName }}
	func (x *{{ $inMessageName }}) FieldMask() *{{ $methodName }}_FieldMask {
		return new{{ $methodName }}_FieldMask(x, x.{{ $fmField.Name.UpperCamelCase }})
	}

	// new{{ $methodName }}_FieldMask creates a new FieldMask with the given fieldmask
	func new{{ $methodName }}_FieldMask(msg *{{ $inMessageName }}, fieldmask *fieldmaskpb.FieldMask) *{{ $methodName }}_FieldMask {
		fm := &{{ $methodName }}_FieldMask{
			msg:  msg,
			mode: pgfmpb.MaskMode_{{ $methodOpts.Mode }},
			mask: fieldmask,
			req:  make(map[string]struct{}),
			res:  make(map[string]struct{}),
		}

		// Parse existing paths to populate req and res maps
		if fieldmask != nil && len(fieldmask.GetPaths()) > 0 {
			paths := fieldmask.GetPaths()
			fm.req, fm.res = pgfmpb.SplitPaths(paths)
		}

		return fm
	}

	// {{ $methodName }}_FieldMask provides helper functions to deal with FieldMask.
	type {{ $methodName }}_FieldMask struct {
		msg  *{{ $inMessageName }}
		mode pgfmpb.MaskMode
		mask *fieldmaskpb.FieldMask
		req  map[string]struct{}
		res  map[string]struct{}
	}

	// ensureMaskInitialized initializes the mask field in the proto message if nil.
	func (fm *{{ $methodName }}_FieldMask) ensureMaskInitialized() {
		if fm.mask != nil {
			return
		}
		// Use proto reflection to find and initialize the FieldMask field
		refl := fm.msg.ProtoReflect()
		descriptor := refl.Descriptor()
		fields := descriptor.Fields()
		for i := 0; i < fields.Len(); i++ {
			fd := fields.Get(i)
			if fd.Message() != nil && fd.Message().FullName() == "google.protobuf.FieldMask" {
				newMask := &fieldmaskpb.FieldMask{}
				refl.Set(fd, protoreflect.ValueOfMessage(newMask.ProtoReflect()))
				fm.mask = newMask
				return
			}
		}
	}

	// setReqFieldPath adds a path to the request map
	func (fm *{{ $methodName }}_FieldMask) setReqFieldPath(path string) {
		if fm.req == nil {
			fm.req = make(map[string]struct{})
		}
		fm.req[path] = struct{}{}
		fm.ensureMaskInitialized()
		pgfmpb.AddReqPathToFieldMask(fm.mask, path)
	}

	// setResFieldPath adds a path to the response map
	func (fm *{{ $methodName }}_FieldMask) setResFieldPath(path string) {
		if fm.res == nil {
			fm.res = make(map[string]struct{})
		}
		fm.res[path] = struct{}{}
		fm.ensureMaskInitialized()
		pgfmpb.AddResPathToFieldMask(fm.mask, path)
	}

	// hasReqFieldPath checks if a path is in the request map
	func (fm *{{ $methodName }}_FieldMask) hasReqFieldPath(path string) bool {
		if fm == nil || len(fm.req) == 0 {
			return false
		}
		_, exists := fm.req[path]
		return exists
	}

	// hasResFieldPath checks if a path is in the response map
	func (fm *{{ $methodName }}_FieldMask) hasResFieldPath(path string) bool {
		if fm == nil || len(fm.res) == 0 {
			return false
		}
		_, exists := fm.res[path]
		return exists
	}

	// Request returns the Request mask operations
	func (fm *{{ $methodName }}_FieldMask) Request() *{{ $inMessageName }}_Req {
		return &{{ $inMessageName }}_Req{
			fm: fm,
		}
	}

	// Response returns the Response mask operations
	func (fm *{{ $methodName }}_FieldMask) Response() *{{ $inMessageName }}_Res {
		return &{{ $inMessageName }}_Res{
			fm: fm,
		}
	}

{{ template "request_mask" dict "InMessage" $pair.InMessage "OutMessage" $pair.OutMessage "FieldMaskField" $fmField "MethodOptions" $methodOpts "Method" $pair.Method }}

{{ template "response_mask" dict "InMessage" $pair.InMessage "OutMessage" $pair.OutMessage "FieldMaskField" $fmField "MethodOptions" $methodOpts "Method" $pair.Method }}

{{ end }}
